config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'artists#index'

  resources :artists do
    resources :songs, except: [:index, :show]
  end

  resources :songs, only: [:index, :show] do
    member do
      post 'add_favorite'
      delete 'remove_favorite'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :song
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  # index
  def index
    @artists = Artist.all
  end

  # new
  def new
    @artist = Artist.new
  end

  # create
  def create
    @artist = Artist.create(artist_params)
    redirect_to artist_path(@artist)
  end

  #show
  def show
    @artist = Artist.find(params[:id])
  end

  # edit
  def edit
    @artist = Artist.find(params[:id])
  end

  # update
  def update
    @artist = Artist.find(params[:id])
    @artist.update(artist_params)
    redirect_to artist_path(@artist)
  end

  # destroy
  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy
    redirect_to artists_path
  end

  private
  def artist_params
    params.require(:artist).permit(:name, :photo_url, :nationality)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :authenticate_user!, only: [:add_favorite, :remove_favorite]
  # index
  def index
    @songs = Song.all
  end

  # new
  def new
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.new
  end

  # create
  def create
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.create(song_params)
    redirect_to @song
  end

  #show
  def show
    @song = Song.find(params[:id])
  end

  # edit
  def edit
    @artist = Artist.find(params[:artist_id])
    @song = Song.find(params[:id])
  end

  # update
  def update
    @song = Song.find(params[:id])
    @song.update(song_params)
    redirect_to @song
  end

  # destroy
  def destroy
    @song = Song.find(params[:id])
    @song.destroy
    redirect_to songs_path
  end

  def add_favorite
    @song = Song.find(params[:id])
    @song.favorites.create(user: current_user)
    redirect_to :back
  end

  def remove_favorite
    Favorite.find_by(user: current_user, song_id: params[:id]).destroy
    redirect_to :back
  end

  private
  def song_params
    params.require(:song).permit(:title, :album, :preview_url, :artist_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/_form.html.erb
<%= form_for @artist do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :photo_url %>
  <%= f.text_field :photo_url %>

  <%= f.label :nationality %>
  <%= f.text_field :nationality %>

  <%= f.submit %>

<% end %>

app/views/artists/edit.html.erb
<h2>Edit Artist</h2>


<%= render 'form' %>

<%= link_to 'Delete!', artist_path(@artist), method: :delete, class: 'delete' %>

app/views/artists/index.html.erb
<h2>Artists <a href="/artists/new">(+)</a></h2>

<ul>
  <% @artists.each do |artist| %>
    <li>
      <a href="/artists/<%= artist.id %>">
        <%= artist.name %>
      </a>
    </li>
  <% end %>
</ul>

app/views/artists/new.html.erb
<h2>New Artist</h2>

<%= render 'form' %>

app/views/artists/show.html.erb
<h2><%= @artist.name %> <a href="/artists/<%= @artist.id %>/edit">(edit)</a></h2>
<h4><%= @artist.nationality %></h4>

<img class='artist-photo' src="<%= @artist.photo_url %>">

<h3>Songs <%= link_to "(+)", new_artist_song_path(@artist) %></h3>
<ul>
  <% @artist.songs.each do |song| %>
    <li>
      <%= link_to "#{song.title} (#{song.album})", song_path(song) %>
      <!-- Note: will throw an error without proper model definitions + associations  -->
      <% if current_user %>
        <% if song.users.include? current_user %>
          <%= link_to "&hearts;".html_safe, remove_favorite_song_path(song), method: :delete, class: "fav" %>
        <% else %>
          <%= link_to "&hearts;".html_safe, add_favorite_song_path(song), method: :post, class: "no-fav" %>
        <% end %>
      <% end %>
    </li>

  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tunr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1>Tun.r</h1>
  <nav>
    <a href="/songs">Songs</a>
    <a href="/artists">Artists</a>

    <div class="user-info">
      <% if current_user %>
        Welcome, <%= current_user.email %>
        <%= link_to 'Signout', destroy_user_session_path, :method => :delete %>
      <% else %>
        <%= link_to 'Signup', new_user_registration_path %>
        <%= link_to 'Login', new_user_session_path %>
      <% end %>      
    </div>
  </nav>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>

</body>
</html>

app/views/songs/_form.html.erb
<%= form_for([@artist, @song]) do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :album %>
  <%= f.text_field :album %>

  <%= f.label :preview_url %>
  <%= f.text_field :preview_url %>

  <%= f.submit %>

<% end %>

app/views/songs/edit.html.erb
<h2>Edit <%= @song.title  %> </h2>

<div class="edit-form">
  <%= render "form"  %>
</div>

<%= link_to "Back", root_path  %>

app/views/songs/index.html.erb
<h2>Songs</h2>

<ul>
  <% @songs.each do |song| %>
    <li>
      <%= link_to "#{song.title} - #{song.artist.name}",song_path(song) %>
    </li>
  <% end %>
</ul>

app/views/songs/new.html.erb
<h2>New Song</h2>

<%= render 'form' %>

app/views/songs/show.html.erb
<h2><%= @song.title %> <%= link_to "(edit)", edit_artist_song_path(@song.artist, @song)  %> </h2>
<h3>By: <%= @song.artist.name %></h3>

Album: <%= @song.album %></br>

<audio controls src="<%= @song.preview_url %>"></audio>